openapi: 3.1.0
info:
  title: Demo
  description: |
    demo demo demo
  version: 1.0.0

paths:
  /items:
    get:
      summary: demo
      operationId: get-items
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object

              
